version: '3.8'

services:
  articlefetcher:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      NEWS_API_ACCESS_KEY: ${NEWS_API_ACCESS_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}